Models/CurrencyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CurrencyConverter.Models
{
    /**
     * Model class modeling a request towards https://api.exchangeratesapi.io/
     */
    public class CurrencyModel
    {
        /**
         * The first currency in the list. 
         */

        public string FirstCurrency { get; set; }

        /**
         * The second currency in the list
         */
        public string SecondCurrency { get; set; }

        /**
         * The amount of first currency
         */
        [Display(Name = "First currency")]
        public double TotalAmountFirstCurrency { get; set; }

        /**
         * The amount of first currency
         */
        [Display(Name = "Second currency")]
        public double TotalAmountSecondCurrency { get; set; }


    }
}

Pages/Convert.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CurrencyConverter.Http;
using CurrencyConverter.Models;
using CurrencyConverter.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CurrencyConverter.Pages
{
    public class ConvertModel : PageModel
    {
        private readonly HttpRequest httpRequest;
        private Dictionary<string, double> _cachedValues;

        [TempData]
        public string ResultInfo { get; set; }
        

        [BindProperty]
        public CurrencyModel CurencyModel { get; set; }

        [BindProperty]
        public IEnumerable<SelectListItem> Options
        {
            get; set;
        }
        //this is used for one purpose, to send same list as Options to javascript
        //Trying to extract Options didn't work. This is a workaround
        public List<string> CountryList {
            get; set;
        }
        public ConvertModel()
        {
            httpRequest = new HttpRequest();
            _cachedValues = null;
            CurencyModel = new CurrencyModel();
           
            Options = AllCurency.CurrencyName.Values.ToList().Select(o => new SelectListItem
            {
                Value = o,
                Text = o
            }).ToList();
            //this is used for one purpose, to send same list as Options to javascript
            //Trying to extract Options didn't work. This is a workaround
            CountryList = AllCurency.CurrencyName.Values.ToList();
            CountryList.Insert(0, "Select currency");
        }
        //user pressed the button for calculating from the first currency
        public async Task/*<IActionResult>*/ OnPostFirstCurrency()
        {
            await CalculaCurrencysAsync(IsFirstCurrency: true);
        }

        /**
         * calculate between two currencies
         * the parameter IsFirstCurrency tells the method if we are doing the calculation from first or second currency
         */
        public async Task CalculaCurrencysAsync(bool IsFirstCurrency)
        {
            
            if (_cachedValues == null)
            {
                _cachedValues = await httpRequest.BuildCacheAsync();
            }

            double firstRate;
            double secondRate;
            //get the key in dictionary, for example Sweden kronors return SEK
            string firstCurrencyKey = AllCurency.CurrencyName.FirstOrDefault(x => x.Value == CurencyModel.FirstCurrency).Key;
            //get the key in dictionary, for example Danish kronors return DK
            string secondCurrencyKey = AllCurency.CurrencyName.FirstOrDefault(x => x.Value == CurencyModel.SecondCurrency).Key;
            if (string.IsNullOrEmpty(firstCurrencyKey) || string.IsNullOrEmpty(secondCurrencyKey))
            {
                ResultInfo = "Both  currency's must be selected";
                return;
            }

            firstRate = _cachedValues.GetValueOrDefault(firstCurrencyKey);
            secondRate = _cachedValues.GetValueOrDefault(secondCurrencyKey);
            double quota = 0;
            if (firstRate != 0 && secondRate != 0)
            {
                if (IsFirstCurrency)
                {
                    quota = secondRate / firstRate;
                    CurencyModel.TotalAmountSecondCurrency = CurencyModel.TotalAmountFirstCurrency * quota;
                    ResultInfo = CurencyModel.TotalAmountFirstCurrency + " " + CurencyModel.FirstCurrency + " equal " + CurencyModel.TotalAmountSecondCurrency + " " + CurencyModel.SecondCurrency;
                }
                else
                {
                    quota = firstRate / secondRate;
                    CurencyModel.TotalAmountFirstCurrency = CurencyModel.TotalAmountSecondCurrency * quota;
                    ResultInfo = CurencyModel.TotalAmountSecondCurrency + " " + CurencyModel.SecondCurrency + " equal " + CurencyModel.TotalAmountFirstCurrency + " " + CurencyModel.FirstCurrency;

                }

            }
        }

        public async Task OnPostSecondCurrency()
        {
            await CalculaCurrencysAsync(IsFirstCurrency: false);
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CurrencyConverter.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CurrencyConverter.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CurrencyConverter.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Convert.cshtml
@page
@using Newtonsoft.Json;
@model CurrencyConverter.Pages.ConvertModel
@{
    ViewData["Title"] = "Convert";
}

<form method="post">
    <div>
        @Html.DropDownListFor(m => m.CurencyModel.FirstCurrency, new SelectList(Model.Options, "Value", "Text"), "Select currency", new { id = "FirstCurrencyDropDown", @class = "css-class" })

        @Html.TextBoxFor(model => model.CurencyModel.TotalAmountFirstCurrency, new { id = "FirstTextBox", oninput = "OnInputFirstCurrencyEvent()" })

        <script type="text/javascript">
            function OnInputFirstCurrencyEvent() {
                var button = document.getElementById("FirstButton");
                button.click();
            }
        </script>
        <span asp-validation-for="CurencyModel.TotalAmountFirstCurrency" class="text-danger"></span>
    </div>
    <div>
        @Html.DropDownListFor(m => m.CurencyModel.SecondCurrency, new SelectList(Model.Options, "Value", "Text"), "Select currency", new { id = "SecondCurrencyDropDown", @class = "css-class" })
        @Html.TextBoxFor(model => model.CurencyModel.TotalAmountSecondCurrency, new { id = "SecondTextBox", oninput = "OnInputSecondCurrencyEvent()" })
        <script type="text/javascript">
            function OnInputSecondCurrencyEvent() {
                var button = document.getElementById("SecondButton");
                button.click();
            }
        </script>
        <span asp-validation-for="CurencyModel.TotalAmountSecondCurrency" class="text-danger"></span>
    </div>
    <div>
        <button type="submit" style="display: none;" id="FirstButton" asp-page-handler="FirstCurrency">Submit first currency</button>
        <button type="submit" style="display: none;" id="SecondButton" asp-page-handler="SecondCurrency">Submit second currency</button>
    </div>
</form>



<div>
    @if (!string.IsNullOrEmpty(Model.ResultInfo))
    {
        var obj = Model.CurencyModel;
        var options = Model.CountryList;
        string firstCountry = @Model.CurencyModel.FirstCurrency;
        string secoundCountry = Model.CurencyModel.SecondCurrency;
        var firstIndex = options.ToList().FindIndex(elem => elem == firstCountry);
        var secondIndex = options.ToList().FindIndex(elem => elem == secoundCountry);
        if (obj != null)
        {
            var modelAsJson = Json.Serialize(obj);
            var countries = Json.Serialize(options);
            //here are the tricksy part in java script
            //rebuild the ui, by repopulating each element again with appropriate values
            // there exist probably some javascript librarys which updates only those fields which are changed
            <script type="text/javascript">
             var modelAsJson = @modelAsJson;
             var countries = @countries;
             var firstIndex = @firstIndex;
            var secondIndex = @secondIndex;

                console.log(@modelAsJson);
            
            var firstCurrencyName = modelAsJson.firstCurrency;
            console.log(firstCurrencyName);
            var secondCurrencyName = modelAsJson.secondCurrency;
            console.log(secondCurrencyName);
            //used populate first currency textfield (ege 45.3)
            var firstCurrencyAmount = modelAsJson.totalAmountFirstCurrency;
                console.log(firstCurrencyAmount);
            //used populate first currency textfield (ege 45.3)
            var secondyAmount = modelAsJson.totalAmountSecondCurrency;
                    console.log(secondyAmount);
            var firstCurrencyDropDown = document.getElementById("FirstCurrencyDropDown");
            var secondCurrencyDropDown = document.getElementById("FirstCurrencyDropDown");
            if (firstCurrencyDropDown != null ) {
                console.log('secondCurrencyDropDown is not null')
                var select = document.getElementById("FirstCurrencyDropDown");
                select.innerHTML = "";
                var options = countries;
                for (var i = 0; i < options.length; i++) {
                    var opt = options[i];
                    var el = document.createElement("option");
                    el.textContent = opt;
                    el.value = opt;
                    select.appendChild(el);
                }
                document.getElementById("FirstCurrencyDropDown").selectedIndex = firstIndex;

            } else {
                console.log('firstCurrencyDropDown is NULL null');
            }
            if (secondCurrencyDropDown != null) {
                console.log('secondCurrencyDropDown is not null')
                var select = document.getElementById("SecondCurrencyDropDown");
                select.innerHTML = "";
                var options = countries;
                for (var i = 0; i < options.length; i++) {
                    var opt = options[i];
                    var el = document.createElement("option");
                    el.textContent = opt;
                    el.value = opt;
                    select.appendChild(el);
                }
                document.getElementById("SecondCurrencyDropDown").selectedIndex = secondIndex;

            } else {
                console.log('secondCurrencyDropDown is NULL null');
            }
            //populate the textboxes containing the numbers
            var firstTextBox = document.getElementById("FirstTextBox");
            if (firstTextBox != null) {
                console.log('firstTextBoxE not null')
                firstTextBox.value = firstCurrencyAmount.toString();
            } else {
                console.log('firstTextBox IS null')
            }
            var secondTextBox = document.getElementById("SecondTextBox")
            if (secondTextBox != null ) {
                console.log('secondTextBox not null');
                secondTextBox.value = secondyAmount.toString();
            } else {
                console.log('secondTextBox IS NULL null');
            }
            </script>
        }
    }
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>This webapp gives you the possibility to do different conversion from different currency's</p>
        <p>You need to press enter and after that the calculation are performed</p>
        <p>There is no onChange event in razor so no calculation on fly, and on submit the fields are cleared</p>
        <p>This is not what is required from the assignment but razor doesn't support those features</p>
    </div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Currency Converter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CurrencyConverter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Convert">Convert</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CurrencyConverter - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>